arch: ppc64le
group: power-focal

services:
    - docker

before_install:
    - sudo apt update; sudo apt install -y jq; jq --version
    # Currently pointing to test branch code of build-script repo
    #- git clone https://github.com/nikhil-kalbande/build-scripts.git
    #- cd build-scripts; git checkout jen-travis-mig

env:
  global:
    - PACKAGE_NAME="dex"
    - VERSION="v2.35.3"
    - LANGUAGE="Nodejs"

jobs:
  include:
    - stage: Build info
      name: Get Build info details
      script:
        - chmod +x script/read_buildinfo.sh;bash script/read_buildinfo.sh
      workspaces:
        create:
          name: build_cache
          paths:
            - .

    # - stage: Builds
      # name: Build script run
      # workspaces:
        # use: build_cache
      # script: 
        # - source variable.sh
        # - if [ ${VALIDATE_BUILD_SCRIPT} == true ]; then chmod +x script/build_package.sh; bash -x script/build_package.sh; fi    

    # - #stage: Build docker image
      # name: Docker build
      # workspaces:
        # use: build_cache
      # script: 
        # - source variable.sh
        # - echo "BUILD_DOCKER - $BUILD_DOCKER"
        # - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/build_docker.sh; bash -x script/build_docker.sh; fi

    - stage: Run Scanner
      name: Trivy scan
      workspaces:
        use: build_cache
      script:
        - echo "This is trivy scan"
        - pwd; ls -ltr
        - docker images
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/build_docker.sh; bash -x script/build_docker.sh; fi
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/trivy_scan.sh; bash -x script/trivy_scan.sh; fi
    - name: Syft scan
      workspaces:
        use: build_cache
      script:
        - echo "This is syft scan"
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/build_docker.sh; bash -x script/build_docker.sh; fi
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/syft_scan.sh; bash -x script/syft_scan.sh; fi 
    - name: Clair scan
      workspaces:
        use: build_cache
      script: 
        - echo "This is clair scan"
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/build_docker.sh; bash -x script/build_docker.sh; fi
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/clair_scan.sh; bash -x script/clair_scan.sh; fi
        
    - name: Grype scan
      workspaces:
        use: build_cache
      script: 
        - echo "This is Grype scan"
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/build_docker.sh; bash -x script/build_docker.sh; fi
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x script/grype_scan.sh; bash -x script/grype_scan.sh; fi